### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by zetaraku** [zetaraku/NCU-Course-Finder-v4#2]
- [ ] <del>以進度條方式呈現加退選時間</del>
- [x] 學院／系別／類別篩選改為互斥選項
- [x] 確認、補足類別篩選選項
- [ ] <del>新增搜尋列 RegExp 語法使用說明</del>
- [x] 加上 Facebook 專頁連結
- [x] 增加更多進階篩選選項
- [x] 以 JavaScript 改寫資料抓取腳本
- [x] 架設資料來源伺服器
- [ ] <del>導入Redux</del>
- [x] 重構...
